services:
  postgres-db:
    image: postgres:15-alpine
    container_name: spring-auth-db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5