spring.application.name=user

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
# Note: Use a Base64 encoded string of at least 32 characters for the secret
app.jwt.secret=YourSuperSecretKeyForSigningTokensMustBeLongEnough12345
app.jwt.expiration-ms=86400000

# Logging (Useful for debugging security)
logging.level.org.springframework.security=DEBUG
logging.level.feign=DEBUG
logging.level.com.test.user.client=DEBUG

# Inventory Service Configuration
inventory.service.url=http://192.168.1.3:8081